[package]
name = "rust-kpdb"
version = "0.1.0"
authors = ["Martijn Rijkeboer <mrr@sru-systems.com>"]
license = "MIT/Apache-2.0"
description = "Library for reading/writing KeePass 2 and KeePassX databases."
documentation = "https://docs.sru-systems.com/rust-kpdb/0.1.0/kpdb/"
homepage = "https://github.com/sru-systems/rust-kpdb"
repository = "https://github.com/sru-systems/rust-kpdb"
readme = "README.md"
keywords = ["keepass", "keepassx", "kdbx"]

[lib]
name = "kpdb"

[dependencies]
byteorder = "1.0.0"
chrono = "0.2.25"
flate2 = "0.2.14"
rand = "0.3.15"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.22"
secstr = "0.2.1"
uuid = { version = "0.3.1", features = ["v4"] }
xml-rs = "0.3.5"

[dev-dependencies]
quickcheck = "0.4.1"

